### ISSUE TITLE
Issues with some of the new charges

### ISSUE THREAD

**Issue by Azgaar** [Azgaar/Armoria#135]
Here are new charges that are displayed incorrectly on my system (Chrome for Mac). It happens as charges has use elements with the same id that affect one another

<img width="515" alt="image" src="https://github.com/Azgaar/Armoria/assets/26469650/e19c2e1a-4f02-4a3f-a697-b51c0cc594d9">
<img width="507" alt="image" src="https://github.com/Azgaar/Armoria/assets/26469650/e9ac4832-198e-400d-a48c-76c9297e0e58">
<img width="516" alt="image" src="https://github.com/Azgaar/Armoria/assets/26469650/2d8c1294-7572-4047-bfae-50686dd645e2">
<img width="506" alt="image" src="https://github.com/Azgaar/Armoria/assets/26469650/39da7229-17f4-4c48-afe5-771babc95f9f">

**Comment by Azgaar** [comment]
@Blipz, could you please check? It looks some svgs got messed up.

**Comment by Blipz** [comment]
Yes, I can reproduce it with Chrome.

**Comment by Blipz** [comment]
I pushed directly in the repository, hope it's OK.

**Comment by Azgaar** [comment]
Thanks
