### ISSUE TITLE
Support Marshalling

### ISSUE THREAD

**Issue by ChevronTango** [Azgaar/Armoria#164]
It would be great if the app supported marshalling. Both Impalement and Quartering

**Comment by Azgaar** [comment]
Hello. It's already supported, what do you mean exactly? Combining multiple individual coas? If so, that's out of scope

**Comment by ChevronTango** [comment]
Yes. I was specifically referring to Marshalling of multiple arms. Quartering or impaling would be an excellent feature. I do hope you'll consider adding it in the future. The joining of two houses would be great to see.

**Comment by Azgaar** [comment]
That's out of the scope of the tool. If you want, you can work on that feature.
