### ISSUE TITLE
Add stains (Murrey, Sanguine, Tenné)

### ISSUE THREAD

**Issue by Azgaar** [Azgaar/Armoria#23]

**Comment by randomstuff** [comment]
Would it make sense to add [other tincturescarnation](https://en.wikipedia.org/wiki/Tincture_(heraldry)#/media/File:Heraldic_tinctures_diagram.svg as well such as [carnation](https://twitter.com/theheraldrysoc/status/1279111794787856384)?

**Comment by Azgaar** [comment]
No really, all these ones are extremelly rare. But I'm working on system that allows custom tinctures, so anything will be possible
