### ISSUE TITLE
Allow to name COAs

### ISSUE THREAD

**Issue by Azgaar** [Azgaar/Armoria#56]

**Comment by Blipz** [comment]
Does naming COAs imply saving their data in the browser? It would be nice to have a personal gallery filled with previous creations, and the ability to export/import them to/from the disk.

**Comment by Azgaar** [comment]
Generally it's not a well-developed idea.

It would be nice to have, but we cannot store it in browser memory as it gets wiped out regularly. So we will need user system and a database, which may be too much.

**Comment by Blipz** [comment]
I wonder why naming COAs would be useful, then.

**Comment by Azgaar** [comment]
Not sure, probably we can close this item, not a priority.
