### ISSUE TITLE
Add 2nd tincture selection for some charges

### ISSUE THREAD

**Issue by Azgaar** [Azgaar/Armoria#57]

**Comment by Blipz** [comment]
Would you accept contributions for this?

If so, what should the JSON object for a charge look like?

- `{"charge":"rose","t":["gules","or","argent"],...}` (possibly breaking compatibility)
- `{"charge":"rose","t":"gules",otherTinctures:["or","argent"],...}`
- `{"charge":"rose","t":"gules-or-argent"],...}`
- something else?

**Comment by Azgaar** [comment]
> Would you accept contributions for this?

Yes, if it's good and well-formatted.

> should the JSON object for a charge look like?

I don't know, it will be a very significant change. Something like `{"charge":"rose","t":"gules","t2":"or",...}`
