### ISSUE TITLE
Error after changing name when uploading a vector charge

### ISSUE THREAD

**Issue by latiif** [Azgaar/Armoria#58]
### Description

When trying to upload a Vector Charge, you get a pop-up after having selected an `svg` file.

If you change the default name of the vector resource and press _Upload_, you get a `Name must be unique Id!` error message.

This is clearly a bug, as this is the frist time you're uploading the vector file.

__If this _is_ an issue (and not a fluke on my part), I'd love to help out with it.__

### Steps to reproduce

1. Go to the website: [Armoria](https://azgaar.github.io/Armoria/).
1. Click _Upload_ -> _Vector Charge_ -> _browse_ -> Select an SVG file.
1. Change the _name_ field to anything random: `averyuniquename` for example.
1. Click _Upload_.
1. Get the error message: _Name must be unique Id!_.

**Comment by Azgaar** [comment]
Agree, that's clearly a bug. The good thing is that's easy to fix and I'm already working on it :)

**Comment by Azgaar** [comment]
Fixed, please check now (cache clean up may be required)
