### ISSUE TITLE
Blurry renderings

### ISSUE THREAD

**Issue by cristiancanton** [Azgaar/Armoria#63]
Field with small semy gets rendered blurry.

Example: https://armoria.herokuapp.com/?size=1500&format=png&coa=%7B%22t1%22:%22semy_of_crossArrowed-argent-vert-smaller%22,%22shield%22:%22fantasy1%22%7D

**Comment by Azgaar** [comment]
Hello, that's how rasterization works, I have no ideas how I can fix it.

**Comment by cristiancanton** [comment]
As a potential mitigation, could it be possible to create a url that sends the PNG to the browser? Like a direct call to the "Download PNG" of the interface?

**Comment by Azgaar** [comment]
Not sure I got it, it's already sending a request to send a png back.

**Comment by Azgaar** [comment]
Finally fixed, change the rasterization to a newer Rust-based library.
