### ISSUE TITLE
Saving an SVG without a gradient produces a black appearance

### ISSUE THREAD

**Issue by schizoidnightmares** [Azgaar/Armoria#64]
Setting the gradient to "No" will cause the SVG to render as a black background.

A workaround to this is to simply manually edit the SVG file by removing the following near the bottom:
`
  <path class="grad" d="M 10,40 h180 v120 h-180 Z" fill="url(#no)" stroke="#333333" stroke-width="0" style="pointer-events: none;"/>`

Note that this line may appear differently in practice.

**Comment by Azgaar** [comment]
Hello. It looks it's ok for me, can you show a screenshot? It's not super clear.

**Comment by schizoidnightmares** [comment]
> Hello. It looks it's ok for me, can you show a screenshot? It's not super clear.

There's nothing much to show as it appears simply as black.

Create any emblem (the setting I am using is specifically Shield -> Banner -> Flag)...

Options -> Gradient -> No
Save -> Download SVG

This is what I get:
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" width="1233" height="1250" viewBox="0 0 200 200">
  <defs>
    <clipPath id="shield_579533327">
      <path d="M 10,40 h180 v120 h-180 Z"/>
    </clipPath>
    <clipPath id="division_579533327">
      <rect x="0" y="100" width="200" height="100"/>
    </clipPath>
    <g id="mullet8" author="Azgaar" license="https://creativecommons.org/publicdomain/zero/1.0">
      <polygon points="100 60 105.85 85.88 128.28 71.72 114.12 94.15 140 100 114.12 105.85 128.28 128.28 105.85 114.12 100 140 94.15 114.12 71.72 128.28 85.88 105.85 60 100 85.88 94.15 71.72 71.72 94.15 85.88"/>
    </g>
  </defs>
  <g clip-path="url(#shield_579533327)">
    <rect class="field" x="0" y="0" width="200" height="200" fill="#ffe066"/>
    <g class="division" clip-path="url(#division_579533327)">
      <rect x="0" y="0" width="200" height="200" fill="#d7374a"/>
    </g>
    <g class="ordinary" i="0" fill="#85185b" stroke="none" stroke-width="1">
      <path d="m 100,95 c 40,-0.2 100,20 100,20 H 0 c 0,0 60,-19.8 100,-20 z" transform="translate(0 -25)"/>
      <path d="m 100,95 c 40,-0.2 100,20 100,20 H 0 c 0,0 60,-19.8 100,-20 z" transform="translate(0 25) rotate(180 100 100)"/>
      <rect x="0" y="88" width="200" height="24" stroke="none"/>
    </g>
    <g class="charge" i="0" charge="mullet8" fill="#fafafa" stroke="none">
      <use xlink:href="#mullet8" transform="translate(30 30) scale(0.7)"/>
    </g>
  </g>
  <path class="grad" d="M 10,40 h180 v120 h-180 Z" fill="url(#no)" stroke="#333333" stroke-width="0" style="pointer-events: none;"/>
</svg>`

Huh. So it turns out, after testing that in Chrome, it does show normal. However, macOS Big Sur's preview in the Finder displays it as black. It only shows normal in macOS if `<path class="grad" d="M 10,40 h180 v120 h-180 Z" fill="url(#no)" stroke="#333333" stroke-width="0" style="pointer-events: none;"/>` is removed from the SVG.

I am guessing we're both running a different OS, hence why maybe the issue does not appear on your end. Keep in mind, gradients do show up fine on Big Sur finder's preview, only when it is set to "no" does it display as black provided the SVG is left unmodified.

**Comment by schizoidnightmares** [comment]
> Thanks. I have changed the code to not add gradient reference if it's "no". So it should be fine now, please check

Checked and confirmed it is now fixed on my end. I appreciate the fix.

**Comment by Azgaar** [comment]
Thanks for the report, closing
