### ISSUE TITLE
Semy

### ISSUE THREAD

**Issue by Sabermoose19** [Azgaar/Armoria#86]
Upon opening the Semy category in editor, google chrome crashes.
![image](https://user-images.githubusercontent.com/93809613/148657135-e911b4a2-a8ae-43a1-a067-f92ea6efcf80.png)

**Comment by Azgaar** [comment]
Hello. It works fine for me, can you please provide a detailed steps to do to reproduce the issue?

**Comment by Azgaar** [comment]
Cannot reproduce the issue, closing
