### ISSUE TITLE
Scale issue

### ISSUE THREAD

**Issue by Alakihel** [Azgaar/Armoria#89]
Hello Azgaar !

First, sorry in advance, but I have no idea if the issue is linked to my computer or my browser.

The "scale" function does not have any impact on the size of the JPG or the PNG document. I changed it several times but it remained the same. Cache on the browser has been emptied. And extension has been switched OFF and ON.

Let me know if I can help or provide data.

Thanks !

**Comment by Azgaar** [comment]
Will close as I cannot see it anymore.
