### ISSUE TITLE
Sizing Issue

### ISSUE THREAD

**Issue by gkrashos** [Azgaar/Armoria#93]
All of a sudden, the individual coat of arms is sitting half way down the left side of the "creation" window (it used to sit at the top) and when it is downloaded, the armorial shield is tiny against a massive rectangular image size. Have there been any changes to sizing? What's happened? The downloaded versions are now unusable due to their size.

**Comment by Azgaar** [comment]
Hello, there were no changes. Can you please share a screenshot so that it is more clear what is the issue?

**Comment by gkrashos** [comment]
Here are the screen shots
<img width="1335" alt="Screen Shot 2022-05-30 at 9 14 40 am" src="https://user-images.githubusercontent.com/42636048/170896941-3b500c5e-0861-450b-aa41-07876789eba6.png">
<img width="2000" alt="Screen Shot 2022-05-30 at 9 16 14 am" src="https://user-images.githubusercontent.com/42636048/170896956-c5b41eab-5dc0-4071-81aa-252cdd637fd7.png">

**Comment by gkrashos** [comment]
As a follow up, I can see that the "canvas" size for the left hand display area (as above) is set at:

Width: 1200
Height: 8460

This is what appears to be the problem. Can you change the canvas size to 1200 to match up wth the width?
<img width="524" alt="Screen Shot 2022-06-01 at 5 42 39 pm" src="https://user-images.githubusercontent.com/42636048/171359008-5409ca6c-3b1c-4dcc-80a8-453edc1a8bfd.png">

**Comment by Azgaar** [comment]
Hello, is it in Safari? I don't see it in Chrome/FF

**Comment by jhilker1** [comment]
I've noticed this on Firefox, but I will double check the canvas size later today.

**Comment by Azgaar** [comment]
Fixed :)
